Repository xarray-contrib/xbatcher, pull requests merged in 2022-10, with the labels that each got.

#101 Add two sections to release drafter
  .github/release-drafter.yml
Labels: maintenance, skip-changelog

#105 Fix resolved version
  .github/release-drafter.yml
Labels: maintenance, skip-changelog

#107 TFAccessor and _as_xarray_dataarray update
  xbatcher/accessors.py
  xbatcher/tests/test_accessors.py
Labels: feature

#113 Add environment file for asv
  asv_bench/asv.conf.json
  ci/requirements/asv.yml
Labels: maintenance, skip-changelog

#118 Use informative error message for optional dependency imports
  doc/index.rst
  pyproject.toml
  xbatcher/loaders/keras.py
  xbatcher/loaders/torch.py
Labels: maintenance

#117 Specify minimum Python version in project metadata
  pyproject.toml
Labels: maintenance, skip-changelog

#108 Add GitHub workflow for PyPI releases
  .github/workflows/pypi-release.yaml
  doc/contributing.rst
  pyproject.toml
  xbatcher/util/print_versions.py
Labels: maintenance

#119 Update README
  README.rst
Labels: documentation, skip-changelog
