Repository xarray-contrib/xbatcher, pull requests merged in 2022-11, with the labels that each got.

#122 Post-release notes drafter update
  .github/release-drafter.yml
Labels: maintenance, skip-changelog

#114 Update notebook to reflect the most recent changes
  doc/demo.ipynb
Labels: documentation

#125 Use nbsphinx to execute demo notebook
  ci/requirements/doc.yml
  doc/conf.py
  doc/demo.ipynb
Labels: maintenance

#124 Improve tests
  xbatcher/__init__.py
  xbatcher/testing.py
  xbatcher/tests/test_generators.py
Labels: maintenance
