Repository xarray-contrib/xbatcher, pull requests merged in 2024-09, with the labels that each got.

#236 Update pre-commit hooks to use latest versions of ruff and mypy
  .pre-commit-config.yaml
  doc/demo.ipynb
Labels: maintenance

#202 Refactor Pytorch dataset
  xbatcher/loaders/torch.py
  xbatcher/tests/test_torch_loaders.py
Labels: feature

#237 Add documentation for caching feature
  .gitignore
  ci/requirements/doc.yml
  doc/contributing.rst
  doc/index.rst
  doc/user-guide/caching.ipynb
  doc/user-guide/index.rst
Labels: documentation

#238 Add zenodo and citation information
  CITATION.cff
  README.rst
  doc/_static/switcher.json
Labels: maintenance
